#!/usr/bin/env python3
"""Bundle JSON requirement files into _bundle.js for offline HTML viewing."""
import json
from pathlib import Path

HERE = Path(__file__).parent
DATA_DIR = HERE / "data"
OUT = HERE / "_bundle.js"

docs = {}
for f in sorted(DATA_DIR.glob("*.json")):
    key = f.stem  # e.g. "01-product"
    docs[key] = json.loads(f.read_text())

out = f"// Auto-generated by build.py — do not edit\nwindow.__REQ_DATA__ = {json.dumps(docs, indent=2)};\n"
OUT.write_text(out)
print(f"Wrote {len(docs)} docs ({sum(1 for _ in OUT.read_text())} bytes) -> {OUT}")
